dependencies:
- name: arcalosui
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.37
- name: jenkins-x-github-app
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.5
- name: jx-tenant-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.29
