dependencies:
- name: arcalosui
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.43
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.112
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.112
- name: jenkins-x-github-app
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.7
- name: jx-tenant-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.46
